### Ex5A: NumPy Fundamentals
This notebook covers basic NumPy operations such as creating arrays, checking data types,
slicing, and transposing.

In [2]:
# importing library
import numpy as np

## Array Basics

In [5]:
# creating a list for fruits
fruits = ["apple","banana","cherry","date"]
fruits

['apple', 'banana', 'cherry', 'date']

In [7]:
# turning list into array
arr_1 = np.array(fruits) # 1D
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [9]:
# checking data type
arr_1.dtype

dtype('<U6')

Unicode string maxed at 6

In [12]:
# creating second array
arr_2 = np.array([[10,11,12],
                  [13,14,15]]) # 2D
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [14]:
# transposed version of arr_2
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [16]:
# checking to see if arr_2 changed
print(arr_2)

[[10 11 12]
 [13 14 15]]


arr_2 stayed the same

In [19]:
# creating array with odd and even numbers
arr_3 = np.array([[1,3,5],
                  [2,4,6]]) # 2D
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [21]:
# slicing arr_3
arr_4 = np.array([arr_3[0,2], arr_3[1,1]]) # grabbing elements (1D)
print(arr_4)

[5 4]


In [23]:
# creating array with 1's with 2 values
arr_5 = np.ones((2,2,2)) # 3D
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
