# Exercise 1.A NumPy: Manipulating Arrays

In [196]:
#importing library and asigning alias
import numpy as np

## Looping Through Arrays

In [199]:
#creating 2D array
arrA = np.array([[11,12,13],[14,15,16]])

In [201]:
#printing array, ensuring it is 2D
print(f"Dimensions: ",arrA.ndim)
print(f"Array: \n", arrA)

Dimensions:  2
Array: 
 [[11 12 13]
 [14 15 16]]


In [203]:
#looping through array and multiply each row by 2
for x in arrA:
        print(x*2)

[22 24 26]
[28 30 32]


In [205]:
#looping through array and multiply each element in the rows by 2
for x in arrA:
    for y in x:
        print(y*2)

22
24
26
28
30
32


Through the first loop, each row was multiplied. During the second loop, each element was multiplied. The first loop was printed out in 2D but the second loop printed each individual value.

In [208]:
# looping through and printing loop_result
for x in arrA:
    loop_result = x*2
    print(loop_result)
# x is being used as the entire row, so when x*2 happens, the whole row gets multiplied at once instead of by each element

[22 24 26]
[28 30 32]


## Joining and Stacking Arrays

In [211]:
#adding two of the same arrays together on axis 0
joined_array_1 = np.concatenate((arrA,arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [213]:
#adding two of the same arrays together on axis 1
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [215]:
#stacking two of the same arrays on a new axis
stacked_array_1 = np.stack((joined_array_1,joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [217]:
#stacking two arrays with different shapes (error)
stacked_array_2 = np.stack((joined_array_1,joined_array_2))
print(stacked_array_2)
#arrays need to have same shapes to be stacked

ValueError: all input arrays must have the same shape

In [219]:
#concatenate joined_array_1 with arrA on 0 axis
another_joined_array = np.concatenate((joined_array_1,arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [221]:
# concantenate joined_array_1 with arrA on axis 1
another_2 = np.concatenate((joined_array_1,arrA), axis=1)
print(another_2)
#arrays need to have the same number of rows

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [223]:
# creating variables to stack arrays
h = np.hstack((arrA,arrA)) #horizontal stacking (adds columns side by side)

v = np.vstack((arrA,arrA)) #vertical stacking (adding rows on top of each other)

d = np.dstack((arrA,arrA)) #depth stacking (creating a new 3D)

print(f"Horizontal: \n",h) #places arrays next to one another
print(f"\nVertical: \n",v) #places arrays vertically
print(f"\nDepth: \n",d) #stacks arrays like layers

Horizontal: 
 [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

Vertical: 
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Depth: 
 [[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [226]:
# splitting joined_array_1
splitsky = np.array_split(joined_array_1, 2) #splitting into 2
print(splitsky) #displaying 2 separate arrays
# there are 2 arrays and both are 2D

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [228]:
#splititng joined_array_1 again
spliterino = np.array_split(joined_array_1, 3) #splitting into 3
print(spliterino) #displaying 3 separate arrays
# there are 3 arrays, each of them remain 2D, but the last 2 arrays has less rows

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [231]:
# searching and replacing odd numbers with string
result_1 = np.where(arrA % 2 == 0, arrA, 'odd') #search and replace odds
print(result_1) #displaying evens as normal, odds as strings

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [234]:
#creating a 2D array
arrB = np.array([[7,6],
                 [13,5],
                 [7,3]])

#sorting each row in ascending order
arrB_sorted = np.sort(arrB)
print(arrB_sorted) #displaying rows smallest to largest

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [236]:
#using conditional logic to filter
print(f"Original: \n",arrB) #original display

z = arrB < 7 #True if values are less than 7
arrC = arrB[z] # applying condition and pulling those values

print(f"\nTargeted Values: ",arrC) #displaying values that are True

Original: 
 [[ 7  6]
 [13  5]
 [ 7  3]]

Targeted Values:  [6 5 3]


In [238]:
# applying similar structure to create new conditional logic
y = arrB >= 7 #True if values are greater than OR equal to 7
arrD = arrB[y] #applying condition and pulling those values

print(f"Original: \n",arrB) #original display
print(f"\nTargeted Values: ",arrD) # displaying values that are True

Original: 
 [[ 7  6]
 [13  5]
 [ 7  3]]

Targeted Values:  [ 7 13  7]
