# Exercise 1.A NumPy: Manipulating Arrays

In [4]:
#importing library
import numpy as np

## Looping Through Arrays

In [45]:
#creating 2D array
arrA = np.array([[11,12,13],[14,15,16]])

In [53]:
#printing array, ensuring it is 2D
print(arrA.ndim)

2


In [59]:
print(arrA)

[[11 12 13]
 [14 15 16]]


In [61]:
#looping through array and multiply each element by 2
for x in arrA:
        print(x*2)

[22 24 26]
[28 30 32]


In [66]:
for x in arrA:
    for y in x:
        print(y*2)

22
24
26
28
30
32


The only difference is that they start to get seperated from the brackets, but they still end up resulting in the same multiplied number.

In [72]:
for x in arrA:
    for y in x*2:
        print(y)

22
24
26
28
30
32
