# Exercise 1.B NumPy Random

In [2]:
#importing library
import numpy as np

## Generating Random Numbers

In [5]:
# generating random integers (1-20)
r_1 = np.random.randint(1,21,size=2) #creating variable with random numbers into 2 elements
print(f"2 Random Elements: \n",r_1) # displaying results

2 Random Elements: 
 [ 5 17]


In [7]:
# generating random integers (1-20) SIZE: 1 row, 2 columns
r_2 = np.random.randint(1,21,size=(1,2)) #creating new variable with random numbers (size 1x2)
print(f"Random 1 Row, 2 Columns: \n",r_2) #displaying results

Random 1 Row, 2 Columns: 
 [[18  5]]


In [9]:
# generating random floats (0-1) SIZE: 2 rows, 1 column
r_3 = np.random.rand(2,1) #using rand to create new variable with random floats (2x1)
print(f"Random 2 Rows, 1 Column (floats): \n",r_3) #displaying results

Random 2 Rows, 1 Column (floats): 
 [[0.43591532]
 [0.16732706]]


In [11]:
# generating random integers (20-100) SIZE: 4 rows, 5 columns
r_4 = np.random.randint(20,101,size=(4,5)) #creating new variable with random numbers (size 4x5)
print(f"Random 4 Rows, 5 Columns: \n",r_4) #displaying results

Random 4 Rows, 5 Columns: 
 [[34 52 85 97 44]
 [49 82 40 85 80]
 [27 80 54 94 42]
 [26 97 39 49 99]]


In [13]:
# generating random floats (0-1) SIZE: 4 rows, 5 columns
r_5 = np.random.rand(4,5) # creating new variable with random floats (4x5)
print(f"Random 4 Rows, 5 Columns (floats): \n",r_5) # displaying results

Random 4 Rows, 5 Columns (floats): 
 [[0.90812809 0.33323022 0.83149871 0.78846453 0.28784515]
 [0.2620619  0.50735501 0.40764353 0.22508986 0.13491822]
 [0.09647028 0.72564399 0.50599172 0.42568767 0.21427082]
 [0.97183817 0.48117492 0.77902796 0.95371289 0.39162058]]


## Generating Random Choices from an Array

In [16]:
# creating a 1D array for student names
students = np.array(["Alexus","Luis O.","Naomi",
                     "Alondra","Victoria","Blake",
                     "Corey","Lorah","Lesley",
                     "Sonia","Luis A.","Charles"])

print(f"Sec 12: \n", students) #displaying list of names

Sec 12: 
 ['Alexus' 'Luis O.' 'Naomi' 'Alondra' 'Victoria' 'Blake' 'Corey' 'Lorah'
 'Lesley' 'Sonia' 'Luis A.' 'Charles']


In [18]:
# creating new variable to call on a student randomly
call_on = np.random.choice(students) #randomly select
print(f"Student to Call on: \n", call_on) #displaying output

Student to Call on: 
 Alexus


In [20]:
# creating a new variable to choose a random sampling
breakout_groups = np.random.choice(students, size=(3,4)) #3 rows, 4 columns
print(f"Breakout Groups: \n",breakout_groups) #displaying output
# this method displayed students being repeated and also not showing all students

Breakout Groups: 
 [['Sonia' 'Victoria' 'Naomi' 'Charles']
 ['Blake' 'Lorah' 'Blake' 'Alexus']
 ['Luis A.' 'Blake' 'Lorah' 'Corey']]


In [22]:
#creating new variable to choose random students with probabilities
students_pvalues = [0.30,0.10,0.05, #0.30 (30%) more likely
                    0.05,0.10,0.10,
                    0.05,0.10,0.05,
                    0.05,0.05,0.00] #0.00 (0%) less likely

call_on_weighted = np.random.choice(students, size=5, p=students_pvalues) #creating random choice
print(f"Students Being Called on: \n",call_on_weighted) #displaying results

Students Being Called on: 
 ['Luis A.' 'Alexus' 'Alexus' 'Alexus' 'Victoria']


## Generating a Normal Distribution

In [25]:
#creating new variable for random distribution curve
bell_curve = np.random.normal(10,5, size=(4,5)) # peak curve:10,standdev:5, size:4x5
print(f"Bell Curve: \n",bell_curve) #displaying results

Bell Curve: 
 [[13.13650225 10.00414273  6.81771609  9.1953421  18.84609755]
 [16.09638468 16.0700037  13.54829218  2.70676191  6.46799951]
 [10.03933531 11.49329328  5.11973612  5.17264222 17.27778683]
 [15.49440405  8.95235785  4.30198869 14.71932728  6.02852831]]
