# Exercise 1.B NumPy Random

In [94]:
#importing library
import numpy as np

## Generating Random Numbers

In [97]:
# generating random integers (1-20)
r_1 = np.random.randint(1,21,size=2) #creating variable with random numbers into 2 elements
print(f"2 Random Elements: \n",r_1) # displaying results

2 Random Elements: 
 [ 5 16]


In [99]:
# generating random integers (1-20) SIZE: 1 row, 2 columns
r_2 = np.random.randint(1,21,size=(1,2)) #creating new variable with random numbers (size 1x2)
print(f"Random 1 Row, 2 Columns: \n",r_2) #displaying results

Random 1 Row, 2 Columns: 
 [[20  2]]


In [101]:
# generating random floats (0-1) SIZE: 2 rows, 1 column
r_3 = np.random.rand(2,1) #using rand to create new variable with random floats (2x1)
print(f"Random 2 Rows, 1 Column (floats): \n",r_3) #displaying results

Random 2 Rows, 1 Column (floats): 
 [[0.50955832]
 [0.64384304]]


In [103]:
# generating random integers (20-100) SIZE: 4 rows, 5 columns
r_4 = np.random.randint(20,101,size=(4,5)) #creating new variable with random numbers (size 4x5)
print(f"Random 4 Rows, 5 Columns: \n",r_4) #displaying results

Random 4 Rows, 5 Columns: 
 [[54 57 46 38 40]
 [82 95 80 80 34]
 [90 27 77 40 93]
 [40 97 77 75 80]]


In [105]:
# generating random floats (0-1) SIZE: 4 rows, 5 columns
r_5 = np.random.rand(4,5) # creating new variable with random floats (4x5)
print(f"Random 4 Rows, 5 Columns (floats): \n",r_5) # displaying results

Random 4 Rows, 5 Columns (floats): 
 [[0.14634351 0.76582028 0.8217066  0.595655   0.22061493]
 [0.79161182 0.20643705 0.49503097 0.92953001 0.20705829]
 [0.08982136 0.10382153 0.49144052 0.42999299 0.19933015]
 [0.79889869 0.69995036 0.95137913 0.51148658 0.02055587]]


## Generating Random Choices from an Array

In [108]:
# creating a 1D array for student names
students = np.array(["Alexus","Luis O.","Naomi",
                     "Alondra","Victoria","Blake",
                     "Corey","Lorah","Lesley",
                     "Sonia","Luis A.","Charles"])

print(f"Sec 12: \n", students) #displaying list of names

Sec 12: 
 ['Alexus' 'Luis O.' 'Naomi' 'Alondra' 'Victoria' 'Blake' 'Corey' 'Lorah'
 'Lesley' 'Sonia' 'Luis A.' 'Charles']


In [110]:
# creating new variable to call on a student randomly
call_on = np.random.choice(students) #randomly select
print(f"Student to Call on: \n", call_on) #displaying output

Student to Call on: 
 Corey


In [112]:
# creating a new variable to choose a random sampling
breakout_groups = np.random.choice(students, size=(3,4)) #3 rows, 4 columns
print(f"Breakout Groups: \n",breakout_groups) #displaying output
# this method displayed students being repeated and also not showing all students

Breakout Groups: 
 [['Alondra' 'Lesley' 'Alondra' 'Naomi']
 ['Corey' 'Charles' 'Luis A.' 'Alexus']
 ['Lorah' 'Lesley' 'Luis A.' 'Alexus']]


In [114]:
#creating new variable to choose random students with probabilities
students_pvalues = [0.30,0.10,0.05, #0.30 (30%) more likely
                    0.05,0.10,0.10,
                    0.05,0.10,0.05,
                    0.05,0.05,0.00] #0.00 (0%) less likely

call_on_weighted = np.random.choice(students, size=5, p=students_pvalues) #creating random choice
print(f"Students Being Called on: \n",call_on_weighted) #displaying results

Students Being Called on: 
 ['Luis O.' 'Luis O.' 'Victoria' 'Luis A.' 'Alexus']


## Generating a Normal Distribution

In [117]:
#creating new variable for random distribution curve
bell_curve = np.random.normal(10,5, size=(4,5)) # peak curve:10,standdev:5, size:4x5
print(f"Bell Curve: \n",bell_curve) #displaying results

Bell Curve: 
 [[14.91949586 15.5576815  17.47440221 16.84658248 16.65975692]
 [11.81920613  6.1132377  12.8182605   6.77446119  0.95376282]
 [ 6.36768376  9.96807811  9.74756035 13.67872859 -3.49001747]
 [12.62011366 17.82223777  6.08944378 14.84399265 13.56114014]]
