# Exercise 1.C Performing operations on arrays

In [76]:
#importing library
import numpy as np

## Sample Arrays

In [79]:
#creating 5 variables that contain random sample arrays
r_1 = np.random.randint(1,21,size=2) #example 1
r_2 = np.random.randint(1,21,size=(1,2)) #example 2
r_3 = np.random.rand(2,1) #example 3
r_4 = np.random.randint(20,101,size=(4,5)) #example 4
r_5 = np.random.rand(4,5) #example 5

#displaying outputs
print(f"r_1: \n",r_1)
print(f"\nr_2: \n",r_2)
print(f"\nr_3: \n",r_3)
print(f"\nr_4: \n",r_4)
print(f"\nr_5: \n",r_5)

r_1: 
 [12  3]

r_2: 
 [[ 1 14]]

r_3: 
 [[0.67154929]
 [0.26623701]]

r_4: 
 [[61 26 43 20 35]
 [85 91 48 30 51]
 [86 77 83 80 75]
 [68 85 82 35 34]]

r_5: 
 [[0.38147881 0.79052587 0.85574314 0.80274328 0.04054496]
 [0.32952648 0.42475055 0.32309972 0.15186007 0.81014171]
 [0.39665763 0.97854004 0.10137699 0.23861507 0.64726134]
 [0.10868759 0.39183422 0.19845727 0.08185983 0.22388124]]


## Permutations

In [82]:
#printing current value of r_4
print(f"Original r_4: \n",r_4)

Original r_4: 
 [[61 26 43 20 35]
 [85 91 48 30 51]
 [86 77 83 80 75]
 [68 85 82 35 34]]


In [84]:
#shuffling r_4
np.random.shuffle(r_4)
print(f"Shuffled r_4: \n",r_4) #displaying result

Shuffled r_4: 
 [[86 77 83 80 75]
 [61 26 43 20 35]
 [68 85 82 35 34]
 [85 91 48 30 51]]


r_4 was shuffled by moving around the rows within the array, but the the elements stayed in their place in each row.

In [87]:
#creating new variable for new_shuffle
new_shuffle = np.random.permutation(r_4) #permutation to shuffle

#printing new results
print(f"New Shuffle: \n",new_shuffle)
print(f"\nComparison to Original: \n",r_4)

New Shuffle: 
 [[85 91 48 30 51]
 [68 85 82 35 34]
 [61 26 43 20 35]
 [86 77 83 80 75]]

Comparison to Original: 
 [[86 77 83 80 75]
 [61 26 43 20 35]
 [68 85 82 35 34]
 [85 91 48 30 51]]


### Shuffle vs Permutation
Shuffle changed the array where the rows are moved around but the values stays in place in their rows.
Permutation changed the array by making a new copy of the array, again, moving around the rows but kept the values in place in their rows.
Both remained 2D, the functions worked in a way where it did shuffle, but the confusion that was encountered is the values not shuffling also.

I would use shuffle to modify the ORIGINAL array, and use permutation to modify a copy, leaving the original unchanged.

## Mathematical Operations

In [91]:
#printing starting values and their shapes
print(f"r_1: \n",r_1)
print(f"\nr_1 shape: \n",r_1.shape)

print(f"\nr_2: \n",r_2)
print(f"\nr_2 shape: \n",r_2.shape)

#adding them together
combined_results = np.add(r_1,r_2)
print(f"\nr_1 + r_2: \n",combined_results)
print(f"\nCombined Results Shape: \n",combined_results.shape)

r_1: 
 [12  3]

r_1 shape: 
 (2,)

r_2: 
 [[ 1 14]]

r_2 shape: 
 (1, 2)

r_1 + r_2: 
 [[13 17]]

Combined Results Shape: 
 (1, 2)


In [93]:
#printing second starting values and their shapes
print(f"r_1: \n",r_1)
print(f"\nr_1 shape: \n",r_1.shape)

print(f"\nr_3: \n",r_3)
print(f"\nr_3 shape: \n",r_3.shape)

#adding them together
combined_results2 = np.add(r_1,r_3)
print(f"\nr_1 + r_3: \n",combined_results2)
print(f"\nCombined Results 2 Shape: \n",combined_results2.shape)

r_1: 
 [12  3]

r_1 shape: 
 (2,)

r_3: 
 [[0.67154929]
 [0.26623701]]

r_3 shape: 
 (2, 1)

r_1 + r_3: 
 [[12.67154929  3.67154929]
 [12.26623701  3.26623701]]

Combined Results 2 Shape: 
 (2, 2)


In [95]:
#printing third starting values and their shapes
print(f"r_2: \n",r_2)
print(f"\nr_2 shape: \n",r_2.shape)

print(f"\nr_4: \n",r_4)
print(f"\nr_4 shape: \n",r_4.shape)

#adding them together
combined_results3 = np.add(r_2,r_4)
print(f"\nr_2 + r_4: \n",combined_results3)
print(f"\nCombined Results 2 Shape: \n",combined_results3.shape)
#resulted in a ValueError because r_2 is (1,2) and r_4 is (4,5) which that shapes do not match

r_2: 
 [[ 1 14]]

r_2 shape: 
 (1, 2)

r_4: 
 [[86 77 83 80 75]
 [61 26 43 20 35]
 [68 85 82 35 34]
 [85 91 48 30 51]]

r_4 shape: 
 (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [97]:
#creating an expression to illustrate what happens incompatibilities
print(f"Testing r_1 + r_4: \n")
np.add(r_1,r_4) #ValueError

Testing r_1 + r_4: 



ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [99]:
print(f"\nTesting r_2 + r_4: \n")
np.add(r_2,r_4) #ValueError


Testing r_2 + r_4: 



ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [101]:
print(f"\nTesting r_3 + r_4: \n")
np.add(r_3,r_4) #ValueError

# All the tests resulted in a ValueError, due to the shapes not matching to r_4


Testing r_3 + r_4: 



ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

In [103]:
#adding array([1]) to r_4
print(f"Shape: ",np.array([1]).shape)
print(f"r_4 + np.array([1]): \n")
print(np.add(r_4,np.array([1])))

Shape:  (1,)
r_4 + np.array([1]): 

[[87 78 84 81 76]
 [62 27 44 21 36]
 [69 86 83 36 35]
 [86 92 49 31 52]]


In [105]:
#adding array([[1]]) to r_4
print(f"Shape: ",np.array([[1]]).shape)
print(f"r_4 + np.array([[1]]): \n")
print(np.add(r_4,np.array([[1]])))

Shape:  (1, 1)
r_4 + np.array([[1]]): 

[[87 78 84 81 76]
 [62 27 44 21 36]
 [69 86 83 36 35]
 [86 92 49 31 52]]


In [107]:
#adding array([1,1,1,1,1]) to r_4
print(f"Shape: ",np.array([1,1,1,1,1]).shape)
print(f"r_4 + np.array([1,1,1,1,1]): \n")
print(np.add(r_4,np.array([1,1,1,1,1])))

Shape:  (5,)
r_4 + np.array([1,1,1,1,1]): 

[[87 78 84 81 76]
 [62 27 44 21 36]
 [69 86 83 36 35]
 [86 92 49 31 52]]


In [109]:
#adding array([[1],[1]]) to r_4
print(f"Shape: ",np.array([[1],[1]]).shape)
print(f"r_4 + np.array([[1],[1]]): \n")
print(np.add(r_4,np.array([[1],[1]]))) #ValueError: shapes do not match

Shape:  (2, 1)
r_4 + np.array([[1],[1]]): 



ValueError: operands could not be broadcast together with shapes (4,5) (2,1) 

### Broadcasting Explanation
Broadcasting works with arrays with different shapes, to be stretched from the smaller array to match the largest.
The values gets repeated across each other to try and line up the shapes. 
Using the add function took each value and added it to position to match after broadcasting.
The final shape will become a larger array.

## Rounding

In [113]:
#printing r_3
print(f"r_3: \n",r_3)
print(f"\nr_3 shape: \n",r_3.shape)

r_3: 
 [[0.67154929]
 [0.26623701]]

r_3 shape: 
 (2, 1)


In [115]:
#rounding using trunc
print(f"trunc(r_3): \n",np.trunc(r_3))

trunc(r_3): 
 [[0.]
 [0.]]


In [117]:
#rounding using fix
print(f"fix(r_3): \n",np.fix(r_3))

fix(r_3): 
 [[0.]
 [0.]]


In [119]:
#rounding using floor
print(f"floor(r_3): \n",np.floor(r_3))

floor(r_3): 
 [[0.]
 [0.]]


In [121]:
#rounding using ceil
print(f"ceil(r_3): \n",np.ceil(r_3))

ceil(r_3): 
 [[1.]
 [1.]]


In [123]:
#rounding 2 decimal places
print(f"round(r_3): \n",np.round(r_3,2))

round(r_3): 
 [[0.67]
 [0.27]]


## Cumulative Operations

In [126]:
# displaying r_4 using different operations
print(f"r_4: \n",r_4) #displaying r_4
print(f"\nr_4 shape: \n",r_4.shape)

r_4: 
 [[86 77 83 80 75]
 [61 26 43 20 35]
 [68 85 82 35 34]
 [85 91 48 30 51]]

r_4 shape: 
 (4, 5)


In [128]:
# sum of all values in r_4
print(f"Sum of all values in r_4: \n",np.sum(r_4))

Sum of all values in r_4: 
 1195


In [130]:
# sum along axis 0
print("Sum along axis 0: \n",np.sum(r_4,axis=0))

Sum along axis 0: 
 [300 279 256 165 195]


In [132]:
# sum along axis 1
print("Sum along axis 1: \n", np.sum(r_4,axis=1))

Sum along axis 1: 
 [401 185 304 305]


In [134]:
# cumulative sum (rolling total)
print("Cumulative sum of all values: \n",np.cumsum(r_4))

Cumulative sum of all values: 
 [  86  163  246  326  401  462  488  531  551  586  654  739  821  856
  890  975 1066 1114 1144 1195]


In [136]:
# cumulative sum along axis 0
print("Cumulative sum along axis 0: \n",np.cumsum(r_4,axis=0))

Cumulative sum along axis 0: 
 [[ 86  77  83  80  75]
 [147 103 126 100 110]
 [215 188 208 135 144]
 [300 279 256 165 195]]


## Grocery Problem

In [139]:
#creating two new variables
bag1 = np.array([2,3,4,0]) #2 veggies, 3 fruits, 4 snacks, 0 drinks
bag2 = np.array([4,0,1,2]) #4 veggies, 0 fruits, 1 snacks, 2 drinks

#displaying bag1 & bag2
print(f"bag1:",bag1)
print(f"bag2:",bag2)

bag1: [2 3 4 0]
bag2: [4 0 1 2]


In [141]:
# total items in each bag
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

#displaying output
print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [143]:
#total items in each category
category_totals = bag1 + bag2

veg, fruit, snacks, bev = category_totals #categories

#displaying output
print(f"There are {veg} vegetables, {fruit} fruits, {snacks} boxes of snacks, {bev} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, 2 beverages in the two grocery bags.


## Teamwork

In [146]:
# Ali's report
ali = np.array([5,4,6,4,2]) #doors,Mon,Tue,Wed,Thu,Fri
print("Ali:",ali) #displaying results

Ali: [5 4 6 4 2]


In [148]:
# Ben's report
ben = np.array([0,5,5,3,4]) #doors,Mon,Tue,Wed,Thu,Fri
print("Ben:",ben) #displaying results

Ben: [0 5 5 3 4]


In [150]:
# Carla's report
carla = np.array([3,6,0,3,4]) #doors,Mon,Tue,Wed,Thu,Fri
print("Carla:",carla) #displaying results

Carla: [3 6 0 3 4]


In [152]:
#compiling all three reports into a single array
all_knocks = np.array([ali,ben,carla])
print(f"All Knocks: \n",all_knocks) #displaying results

All Knocks: 
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [154]:
#total number of doors each person knocked
ali_total = np.sum(ali)
ben_total = np.sum(ben)
carla_total = np.sum(carla)

#total as a group
group_total = np.sum(all_knocks)

print(f"Ali knocked on {ali_total} doors.")
print(f"Ben knocked on {ben_total} doors.")
print(f"Carla knocked on {carla_total} doors.")
print(f"The group collectively knocked on {group_total} doors.")

Ali knocked on 21 doors.
Ben knocked on 17 doors.
Carla knocked on 16 doors.
The group collectively knocked on 54 doors.


In [156]:
#daily totals across the three
daily_totals = np.sum(all_knocks,axis=0) #sum on axis 0
print(f"Daily Totals:",daily_totals)

#rolling total
rolling_knocks = np.cumsum(daily_totals) #cumulative sum
print(f"\nRolling Door-Knock Totals:",rolling_knocks)

#estimated votes
estimated_votes = rolling_knocks*0.5 #half of rolling knocks
print(f"\nEstimated Rolling Votes:",estimated_votes)

Daily Totals: [ 8 15 11 10 10]

Rolling Door-Knock Totals: [ 8 23 34 44 54]

Estimated Rolling Votes: [ 4.  11.5 17.  22.  27. ]
